version: 2

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
  clj-kondo: &clj-kondo
    lint-command: 'clj-kondo --lint'
    lint-formats:
      - '%f:%l:%c:\ Parse\ %t%*[^:]:\ %m'
      - '%f:%l:%c:\ %t%*[^:]:\ %m'

languages:
  vim:
    - <<: *vim-vint
  clojure:
    - <<: *clj-kondo
