[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  if ! executable('node')
    let g:coc_node_path = '/usr/local/bin/node'
  endif

  let g:coc_global_extensions = [
       \ 'coc-copilot',
       \ 'coc-deno',
       \ 'coc-diagnostic',
       \ 'coc-eslint',
       \ 'coc-lines',
       \ 'coc-prettier',
       \ 'coc-tsdetect',
       \ 'coc-tsserver',
       \ ]
  " coc-tsserver と一緒に入っていると ts プロジェクトにて
  " tsserver を無効にする .vim/coc-settings.json がプロジェクトルートに作成さ
  " れてしまうので一旦 uninstall

  function! s:coc_check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~# '\s'
  endfunction

  iunmap <expr><tab>
  inoremap <silent><expr> <TAB> coc#pum#visible()
    \ ? coc#pum#next(1)
    \ : <SID>coc_check_back_space()
    \   ? "\<Tab>"
    \   : coc#refresh()

  inoremap <expr> <CR> coc#pum#visible() ? coc#_select_confirm() : "\<CR>"
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

  nmap <silent> <LocalLeader>cc  <plug>(coc-codeaction-selected)iw

  nmap <silent> <LocalLeader>cr  <Cmd>call CocAction('rename')<CR>
  nmap <silent> <LocalLeader>cd  <Cmd>call CocAction('jumpDefinition')<CR>
  nmap <silent> <LocalLeader>cf  <Cmd>call CocAction('jumpReferences')<CR>
  nmap <silent> <LocalLeader>cic <Cmd>call CocAction('showIncomingCalls')<CR>

  command! LspRenameSymbol :call CocActionAsync('rename')
  "command! LspRenameSymbol :call CocAction('rename')

  aug MyCocSetting
    au!
    au FileType typescript,typescriptreact,css nnoremap <buffer> K :call CocActionAsync('doHover')<CR>
  aug END

  highlight MyCocInlayHint ctermfg=5 guifg=#3b474f
  hi link CocInlayHint MyCocInlayHint
'''
