[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = '''
  if ! executable('deno')
    let g:denops#deno = printf('%s/.deno/bin/deno', $HOME)
  endif

  if g:denops_dev
    call denops#plugin#check_type()
  else
    let g:denops_server_addr = '127.0.0.1:32123'
  endif
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
hook_source = '''
  let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
  nmap <LocalLeader>/ <Cmd>FuzzyMotion<CR>
'''

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'mracos/mermaid.vim'

# [[plugins]]
# repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_source = '''
  " Important!!
  if has('termguicolors')
    set termguicolors
  endif

  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

  colorscheme iceberg

  if has('nvim')
    highlight! link FloatBorder Conceal

    highlight! link StatusLine SpecialKey
    highlight! link StatusLineNC Whitespace
    highlight! link WinSeparator Whitespace

    " highlight! link StatusLine Directory
    " highlight! link StatusLineNC Conceal
    " highlight! link WinSeparator Conceal
  endif
'''

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'vim-test/vim-test'
depends = ['tpope/vim-dispatch']
hook_source = '''
  aug MyVimTestSetting
    au!
    au FileType typescript,typescriptreact nmap <silent> <leader>tt :TestNearest<CR>
    au FileType typescript,typescriptreact nmap <silent> <leader>tb :TestFile<CR>
  aug END

  let g:test#javascript#runner = 'jest'
  let test#javascript#jest#executable = 'yarn jest'
  let test#strategy = "dispatch"
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-submode'
hook_source = '''
  let g:submode_timeout = 0
  try
    call submode#enter_with('window', 'n', '', '<C-w><C-w>', '<Nop>')
    call submode#leave_with('window', 'n', '', '<Esc>')
    call submode#map('window', 'n', '', 'j', '<C-w>j')
    call submode#map('window', 'n', '', 'J', '<C-w>J')
    call submode#map('window', 'n', '', 'k', '<C-w>k')
    call submode#map('window', 'n', '', 'K', '<C-w>K')
    call submode#map('window', 'n', '', 'l', '<C-w>l')
    call submode#map('window', 'n', '', 'L', '<C-w>L')
    call submode#map('window', 'n', '', 'h', '<C-w>h')
    call submode#map('window', 'n', '', 'H', '<C-w>h')
    call submode#map('window', 'n', '', 's', '<C-w>s')
    call submode#map('window', 'n', '', 'v', '<C-w>v')
    call submode#map('window', 'n', '', 'x', ':q<CR>')
    call submode#map('window', 'n', '', '>', '<C-w>5>')
    call submode#map('window', 'n', '', '<', '<C-w>5<lt>')
    call submode#map('window', 'n', '', '+', '<C-w>5+')
    call submode#map('window', 'n', '', '-', '<C-w>5-')

    " c.f. vim-iced jumping signs
    call submode#enter_with('sign_jump', 'n', '', '<LocalLeader>n', ':<C-u>IcedJumpToNextSign<CR>')
    call submode#enter_with('sign_jump', 'n', '', '<LocalLeader>N', ':<C-u>IcedJumpToPrevSign<CR>')
    call submode#leave_with('sign_jump', 'n', '', '<Esc>')
    call submode#map('sign_jump', 'n', '', 'n', ':<C-u>IcedJumpToNextSign<CR>')
    call submode#map('sign_jump', 'n', '', 'N', ':<C-u>IcedJumpToPrevSign<CR>')

    " " c.f. ftplugin/clojure.vim
    " call submode#enter_with('slurp', 'n', '', '<LocalLeader><', ':<C-u>DPSlurpSexp<CR>')
    " call submode#enter_with('slurp', 'n', '', '<LocalLeader>>', ':<C-u>DPBarfSexp<CR>')
    " call submode#leave_with('slurp', 'n', '', '<Esc>')
    " call submode#map('slurp', 'n', '', 's', ':<C-u>DPSlurpSexp<CR>')
    " call submode#map('slurp', 'n', '', 'b', ':<C-u>DPBarfSexp<CR>')

    call submode#enter_with('slurp', 'n', '', '<LocalLeader>ks', ':<C-u>IcedSlurp<CR>')
    call submode#enter_with('slurp', 'n', '', '<LocalLeader>kb', ':<C-u>IcedBarf<CR>')
    call submode#leave_with('slurp', 'n', '', '<Esc>')
    call submode#map('slurp', 'n', '', 's', ':<C-u>IcedSlurp<CR>')
    call submode#map('slurp', 'n', '', 'b', ':<C-u>IcedBarf<CR>')
  catch
    echo 'submode is not installed'
  endtry
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'seroqn/foldmaker.vim'

[[plugins]]
repo = 'github/copilot.vim'
hook_source = '''
  imap <silent><script><expr> <C-a> copilot#Accept("\<CR>")
  let g:copilot_no_tab_map = v:true

  let g:copilot_filetypes = #{
        \ gitcommit: v:true,
        \ markdown: v:true,
        \ text: v:true,
        \ ddu-ff-filter: v:false,
        \ }
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
#if = '!has("nvim")'
hook_add = '''
  if !has('gui_running')
    set t_Co=256
  endif

  function! MyCocStatus() abort
    return get(g:, 'coc_status', '')
  endfunction

  let g:lightline = {
        \   'colorscheme': 'iceberg',
        \   'active': { 'left': [], 'right': [] },
        \   'separator': { 'left': "\ue0b4", 'right': "\ue0b6"},
        \   'subseparator': { 'left': "\ue0b5", 'right':  "\ue0b7" },
        \   'tabline': {
        \     'left': [[ 'tabs' ]],
        \     'right': [['filetype', 'bufnum' ], ['anzu'], ['iced']]
        \   },
        \   'component_function': {
        \     'anzu': 'anzu#search_status',
        \     'iced': 'iced#repl#status',
        \     'iced_multi_session': 'iced_multi_session#current',
        \     'coc_status': 'MyCocStatus',
        \   },
        \ }
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
if = '!has("nvim")'
hook_add = '''
  nmap gj <Plug>(GitGutterNextHunk)
  nmap gk <Plug>(GitGutterPrevHunk)

  aug MyGitGutterSetting
    au!
    au BufWritePost * GitGutter
  aug END
'''

[[plugins]]
repo = '~/src/github.com/liquidz/vim-fixme'
